### ISSUE TITLE
Flash failure / Camera Crash 

### ISSUE THREAD

**Issue by AdmiralRedRum** [adrian-bl-yuga/device-sony-c6603#16]
This seems to happen whenever any "heart rate monitoring" type app tries to gain access to camera. On runtastic heart rate, the app warns that "your phone doesn't have LED", then when you proceed anyway, it acts like you dont even have a camera, nothing happens. On Azumio's Heart rate app, the app starts, the moment it tries to start the flash/camera, you see multiple flashes of light from LED, then Camera crashes, needs a reboot.

Currrently on 5.0.4

**Comment by adrian-bl** [comment]
Please provide a logcat

**Comment by AdmiralRedRum** [comment]
http://www.mediafire.com/view/33y7uvqtw9iv75a/2014-11-27-08-46-31.txt

Will this do?

**Comment by adrian-bl-yuga** [comment]
The application seems to actually crash the ActivityManager:

F/ActivityManager(  694): Activity Manager Crash
F/ActivityManager(  694): java.lang.IllegalStateException: Bad magic number for Bundle: 0x1
F/ActivityManager(  694):       at android.os.BaseBundle.readFromParcelInner(BaseBundle.java:1346)
F/ActivityManager(  694):       at android.os.BaseBundle.<init>(BaseBundle.java:90)
F/ActivityManager(  694):       at android.os.Bundle.<init>(Bundle.java:68)
F/ActivityManager(  694):       at android.os.Parcel.readBundle(Parcel.java:1698)
F/ActivityManager(  694):       at android.os.Parcel.readBundle(Parcel.java:1682)
F/ActivityManager(  694):       at android.content.Intent.readFromParcel(Intent.java:7236)
F/ActivityManager(  694):       at android.content.Intent.<init>(Intent.java:7202)
F/ActivityManager(  694):       at android.content.Intent$1.createFromParcel(Intent.java:7193)
F/ActivityManager(  694):       at android.content.Intent$1.createFromParcel(Intent.java:7191)
F/ActivityManager(  694):       at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:429)
F/ActivityManager(  694):       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2407)
F/ActivityManager(  694):       at android.os.Binder.execTransact(Binder.java:446)

This looks like bug in Android itself: Does the app actually work on any 5.x devices?

**Comment by AdmiralRedRum** [comment]
Not really sure. Nobody has posted anything in the comments area (guessing nobody has lollipop yet). Runtastic heart rate is a paid app. And they didn't update/respond . azumio only recently updated their app to coincide with lollipop launch.

Let me try to get the logs for runtastic.

**Comment by AdmiralRedRum** [comment]
http://www.mediafire.com/view/116vkfwvd4acs41/runtastic.txt

These are the logs to the runtastic app. It crashes the activity manager too. However. The weird thing is it does not crash the camera like azumio's app does. In axumio's case, a reboot is always needed to use camera.  

Azumio 's app was actually updated on Nov 25. This iz sad

I have a noobish question, if these apps cant get access to the camera when they request to, how come camera apps don't crash it?

**Comment by planarteapot** [comment]
For me the android default camera app starts up, then shows picture in the wrong aspect ratio, then crashes.

However the Google Camera from Play store works fine.
